config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'contact', to: 'pages#contact', as: :contact

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cellars do
    resources :bouteilles, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :vins


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bouteille.rb
class Bouteille < ApplicationRecord
  belongs_to :cellar
  belongs_to :vin
end

app/models/cellar.rb
class Cellar < ApplicationRecord
  has_many :bouteilles
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cellars
end

app/models/vin.rb
class Vin < ApplicationRecord
  has_many :bouteilles

  def complete_denomination
    "#{categorie.upcase} #{localite.upcase} #{appellation} #{domaine} #{couleur}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bouteilles_controller.rb
class BouteillesController < ApplicationController
  def index
    @bouteilles = Bouteille.all
    @cellar = Cellar.find(params[:cellar_id])
  end


  def new
    @cellar = Cellar.find(params[:cellar_id])
    @bouteille = Bouteille.new
  end

  def create
    @bouteille = Bouteille.new(bouteille_params)
    @bouteille.cellar = Cellar.find(params[:cellar_id])
    @bouteille.vin = Vin.find(params[:bouteille][:vin_id])
    @bouteille.save

    redirect_to cellar_path(params[:cellar_id])
  end


  def edit
    @bouteille = Bouteille.find(params[:id])
    @cellar = Cellar.find(params[:cellar_id])

  end

  def update
    @bouteille = Bouteille.find(params[:id])
    @cellar = Cellar.find(params[:cellar_id])

    @bouteille.update(bouteille_params)
    redirect_to cellar_path(params[:cellar_id])
  end

  def destroy
    @bouteille = Bouteille.find(params[:id])
    cellar = @bouteille.cellar
    @bouteille.destroy
    redirect_to cellar_path(cellar)
  end


  private

  def bouteille_params
    params.require(:bouteille).permit(:millesime)
  end
end

app/controllers/cellars_controller.rb
class CellarsController < ApplicationController

  def index
    @user = current_user

    @cellars = Cellar.all
    @cellar = Cellar.new
  end

  def show
    @cellar = Cellar.find(params[:id])
    @bouteilles = @cellar.bouteilles
  end

  def new
    @cellar = Cellar.new
  end

  def create
    @cellar = Cellar.new(cellar_params)
    @cellar.user = current_user
    @cellar.save

    redirect_to cellars_path
  end


  def destroy
    @cellar = Cellar.find(params[:id])
    @cellar.destroy
    redirect_to cellars_path(current_user)
  end

    private

  def cellar_params
    params.require(:cellar).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def contact
  end

  def about
  end

  def home
  end
end

app/controllers/vins_controller.rb
class VinsController < ApplicationController

  def index
    @vins = Vin.all
    @user = current_user
  end


  def new
    @vin = Vin.new
  end

  def create
    @vin = Vin.new(vin_params)
    @vin.save

    redirect_to vins_path
  end

  def destroy
    @vin = Vin.find(params[:id])
    @vin.destroy
    redirect_to vins_path
  end


  private

  def vin_params
    params.require(:vin).permit(:categorie, :appellation, :contenance, :couleur, :localite, :domaine)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bouteilles_helper.rb
module BouteillesHelper
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/helpers/cellar_helper.rb
module CellarHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vins_helper.rb
module VinsHelper
end

app/views/bouteilles/edit.html.erb
<div class="edit_bottle">

  <div class="etiquette">
    <div class="etiquette_image">
      <%= image_tag "etiquette.png"%>
    </div>
    <div class="bottle_info huge">
      <div class="funky_font hugeX"> <%= @bouteille.vin.appellation.capitalize %>
      </div>
      <br>
      <%= @bouteille.millesime %>
      <br>
      <br>
      <%= @bouteille.vin.localite %>
      <br>
      <%= @bouteille.vin.domaine %>
    </div>
  </div>


  <div class="bu">

    <p> ---- Sortir cette Bouteille de votre Cave ---- </p>  <%= link_to 'Bu', cellar_bouteille_path(params[:id]),
          method: :delete,
          class: "btn btn-secondary btn-sm colorful",
          data: { confirm: "Etes-vous sûr de vouloir supprimer cette bouteille ?" }  %>

  <br>
  <br>

    <p>---- Modifier cette bouteille ----</p>

    <p>
      <%= simple_form_for [@cellar, @bouteille] do |b| %>
        <%= b.association :vin, :collection => Vin.all.order(:appellation), :label_method => :complete_denomination, label: 'Appellation'%>
        <%= b.input :millesime %>
        <%= b.submit "Modifier", class: "btn btn-secondary btn-sm colorful" %>
      <% end %>
    </p>

</div>

app/views/bouteilles/index.html.erb
<div class="navbar-vin">
  <%= link_to cellars_path do %>
  <h1 class="navbar-font">Les caves de Jean L.</h1>
  <% end %>
  <%= link_to vins_path do %>
  <div class="addwine">
  <%=  image_tag "bouteille.png"%>
  </div>
  <% end %>
</div>

<h1>Voici la liste des bouteilles de <%= @cellar.name %></h1>


<ul> <% @bouteilles.each do |b| %>
  <li>
    <%= b.millesime %> - <%= b.vin.appellation %>
  </li>
<% end %>
</ul>

app/views/bouteilles/new.html.erb
<div class="wine_manager">

  <div class="left_part">

    <div class="liste">
      <div class= "alignement">  <%= simple_form_for [@cellar, @bouteille] do |b| %>
        <%= b.association :vin, :collection => Vin.all.order(:appellation), :label_method => :complete_denomination, label: 'Sélectionnez le vin', as: :radio_buttons%>
        <%= b.input :millesime, label: "Entrez l'année - Le Millésime :" %>
        <%= b.submit "Ajouter une bouteille à ma cave", class: "btn btn-secondary btn-sm colorful" %>
      <% end %>
      </div>
    </div>

  </div>

  <div class="right_part">
    <h3>Ajouter en Cave</h3>

  </div>

</div>





<h1>Ajoutez une bouteille de vin référencé à votre cave de <%= @cellar.name %></h1>

app/views/caves/index.html.erb
<div class="navbar-vin">
  <h1 class="navbar-font">Les caves de Jean L.</h1>
</div>

<div class="clickable-card">
  <%= link_to cafe_path(Cave.first) do %>
    <div class="cave_box_cambou">
      <div class="cave_box_text">
        <h2 ><%= Cave.first.name %></h2>
      </div>
    </div>
  <% end %>
</div>
<div class="clickable-card">
  <%= link_to cafe_path(Cave.second) do %>
    <div class="cave_box_gaylussac">
      <div class="cave_box_text">
        <h2 ><%= Cave.second.name %></h2>
      </div>
    </div>
  <% end %>
</div>

<div class="bas-de-page">
  <p>Réalisé par H.L. en Janvier 2019</p>
</div>

app/views/cellars/index.html.erb
<% @user.cellars.each do |c| %>
  <div class="clickable-card">
    <%= link_to cellar_path(c) do %>
      <div class="cave_box_newcellar">
        <div class="cave_box_text">
          <h2 ><%= c.name %></h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class= "newcellar_container">
  <div class = "newcellar_name">
    <%= simple_form_for [@cellar] do |c| %>
      <%= c.input :name, label: "Créez une nouvelle cave" %>
      <%= c.submit "Ajouter", class: "btn btn-secondary btn-sm" %>
    <% end %>
  </div>
</div>



<%= link_to vins_path do %>
  <div class="addwine">
  <%=  image_tag "bouteille.png"%>
  </div>
  <% end %>

app/views/cellars/show.html.erb
<div class= "wine_recap_cambou">

  <div class = "cellar_info">
    <% vin_rouge = [] %>
    <% @bouteilles.each do |b| %>
      <% if b.vin.categorie == "Vin" && b.vin.couleur == "rouge" %>
        <% vin_rouge << b %>
      <% end %>
    <% end %>
  <div class = "number_bottle" >  <%= vin_rouge.length %> </div>

  <div class = "bottle_category"> Vins Rouges </div>
  </div>

  <div class = "cellar_info">
    <% vin_blanc = [] %>
    <% @bouteilles.each do |b| %>
      <% if b.vin.categorie == "Vin" && b.vin.couleur == "blanc" %>
        <% vin_blanc << b %>
      <% end %>
    <% end %>
  <div class = "number_bottle"> <%= vin_blanc.length %> </div>
  <div class = "bottle_category"> Vins Blancs </div>
  </div>

  <div class = "cellar_info">
    <% vin_rose = [] %>
    <% @bouteilles.each do |b| %>
      <% if b.vin.categorie == "Vin" && b.vin.couleur == "rosé" %>
        <% vin_rose << b %>
      <% end %>
    <% end %>
  <div class = "number_bottle"> <%= vin_rose.length %> </div>
  <div class = "bottle_category"> Vins Rosés </div>
  </div>

  <div class = "cellar_info">
    <% champagne = [] %>
    <% @bouteilles.each do |b| %>
      <% if b.vin.categorie == "Champagne" %>
        <% champagne << b %>
      <% end %>
    <% end %>
  <div class = "number_bottle"> <%= champagne.length %> </div>
  <div class = "bottle_category"> Champagnes </div>
  </div>

  <div class = "cellar_info">
    <% petillant = [] %>
    <% @bouteilles.each do |b| %>
      <% if b.vin.categorie == "Petillant" %>
        <% petillant << b %>
      <% end %>
    <% end %>
  <div class = "number_bottle"> <%= petillant.length %> </div>
  <div class = "bottle_category"> Vins Pétillants </div>
  </div>

</div>

<!-- ================================ci-dessous Les listes de vins
 -->

<div class="wine_list">

  <ul class="responsive-table">
      <li class="table-header">
        <div class="colonne-1">Vins Rouges de <%= @cellar.name %></div>
        <div class="col-2">Domaine</div>
        <div class="col-3">Millesime</div>
        <div class="col-4">Apogée</div>
        <div class="col-5"></div>
      </li>
      <% @cellar.bouteilles.each do |b| %>
      <% if b.vin.categorie == "Vin" && b.vin.couleur == "rouge" %>
      <li class="table-row">
        <div class="colonne-1" data-label="Job Id"><%= b.vin.localite  %> <%= b.vin.appellation  %> </div>
        <div class="col-2" data-label="Customer Name"> <%= b.vin.domaine  %></div>
        <div class="col-3" data-label="Amount"> <%= b.millesime  %></div>
        <div class="col-4" data-label="Payment Status">
          <% if b.vin.categorie == "Vin" && b.vin.localite =="Loire Rouge" %>
            <%= b.millesime.to_i + 5 %> "+/- 1 an"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Bordeaux Rouge" %>
            <%= b.millesime.to_i + 7 %> "+/- 3 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Bordeaux Grands Crus" %>
            <%= b.millesime.to_i + 15 %> "+/- 5 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Sud-Ouest" %>
            <%= b.millesime.to_i + 7 %> "+/- 3 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Languedoc et Provence" %>
            <%= b.millesime.to_i + 6 %> "+/- 2 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Côtes du Rhône" %>
            <%= b.millesime.to_i + 5 %> "+/- 1 an"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Côtes du Rhône Grands Crus" %>
            <%= b.millesime.to_i + 15 %> "+/- 5 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Beaujolais" %>
            <%= b.millesime.to_i + 4 %>
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Bourgogne - Saône et Loire" %>
            <%= b.millesime.to_i + 7 %> "+/- 3 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Bourgogne - Côte d'Or" %>
            <%= b.millesime.to_i + 15 %> "+/- 5 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Espagne Rouge" %>
            <%= b.millesime.to_i + 7 %> "+/- 3 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Italie Rouge" %>
            <%= b.millesime.to_i + 12 %> "+/- 3 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Amérique du Sud Rouge" %>
            <%= b.millesime.to_i + 8 %> "+/- 2 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Californie Rouge" %>
            <%= b.millesime.to_i + 8 %> "+/- 2 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Australie Rouge" %>
            <%= b.millesime.to_i + 8 %> "+/- 2 ans"
          <% else %>
            --
          <% end %>
        </div>
        <div class="col-5" data-label="Payment Status"><%= link_to '<i class="fas fa-wine-glass-alt"></i>'.html_safe, edit_cellar_bouteille_path(params[:id],b.id)  %></div>
      </li>
      <% end %>
    <% end %>
  </ul>

</div>

<div class="wine_list">

  <ul class="responsive-table">
      <li class="table-header">
        <div class="colonne-1">Vins Blancs de <%= @cellar.name %></div>
        <div class="col-2">Domaine</div>
        <div class="col-3">Millesime</div>
        <div class="col-4">Apogée</div>
        <div class="col-5"></div>
      </li>
      <% @cellar.bouteilles.each do |b| %>
      <% if b.vin.categorie == "Vin" && b.vin.couleur == "blanc" %>
      <li class="table-row">
        <div class="colonne-1" data-label="Job Id"><%= b.vin.localite  %> <%= b.vin.appellation  %></div>
        <div class="col-2" data-label="Customer Name"> <%= b.vin.domaine  %></div>
        <div class="col-3" data-label="Amount"> <%= b.millesime  %></div>
        <div class="col-4" data-label="Payment Status">
          <% if b.vin.categorie == "Vin" && b.vin.localite =="Alsace" %>
            <%= b.millesime.to_i + 4 %> "+/- 1 an"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Loire Blanc Sec" %>
            <%= b.millesime.to_i + 3 %> "+/- 1 an"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Loire Blanc Moelleux et Liquoreux" %>
            <%= b.millesime.to_i + 15 %> "+/- 5 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Bordeaux Blanc Sec" %>
            <%= b.millesime.to_i + 6 %> "+/- 2 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Bordeaux Blanc Liquoreux" %>
            <%= b.millesime.to_i + 17 %> "+/- 3 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Sud-Ouest Blanc Sec" %>
            <%= b.millesime.to_i + 4 %> "+/- 1 an"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Sud-Ouest Blanc Liquoreux" %>
            <%= b.millesime.to_i + 12 %> "+/- 3 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Languedoc et Provence Blanc" %>
            <%= b.millesime.to_i + 3 %>
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Côtes du Rhône Blanc" %>
            <%= b.millesime.to_i + 3 %> "+/- 1 an"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Bourgogne - Saône et Loire Blanc" %>
            <%= b.millesime.to_i + 4 %>
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Bourgogne - Côte d'Or Blanc" %>
            <%= b.millesime.to_i + 8 %> "+/- 2 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Jura" %>
            <%= b.millesime.to_i + 6 %> "+/- 6 ans"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Alsace" %>
            <%= b.millesime.to_i + 4 %> "+/- 1 an"
          <% else %>
            --
          <% end %>
        </div>
        <div class="col-5" data-label="Payment Status"><%= link_to '<i class="fas fa-wine-glass-alt"></i>'.html_safe, edit_cellar_bouteille_path(params[:id],b.id)  %></div>      </li>
      <% end %>
    <% end %>
  </ul>

</div>
<div class="wine_list">

  <ul class="responsive-table">
      <li class="table-header">
        <div class="colonne-1">Vins Rosés de <%= @cellar.name %></div>
        <div class="col-2">Domaine</div>
        <div class="col-3">Millesime</div>
        <div class="col-4">Apogée</div>
        <div class="col-5"></div>
      </li>
      <% @cellar.bouteilles.each do |b| %>
      <% if b.vin.categorie == "Vin" && b.vin.couleur == "rosé" %>
      <li class="table-row">
        <div class="colonne-1" data-label="Job Id"><%= b.vin.localite  %> <%= b.vin.appellation  %></div>
        <div class="col-2" data-label="Customer Name"> <%= b.vin.domaine  %></div>
        <div class="col-3" data-label="Amount"> <%= b.millesime  %></div>
        <div class="col-4" data-label="Payment Status">
          <% if b.vin.categorie == "Vin" && b.vin.localite =="Languedoc rosé" %>
            <%= b.millesime.to_i + 3 %> "+/- 1 an"
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Provence rosé" %>
            <%= b.millesime.to_i + 3 %>
          <% elsif b.vin.categorie == "Vin" && b.vin.localite =="Rhône rosé" %>
            <%= b.millesime.to_i + 2 %>
          <% else %>
            --
          <% end %>
        </div>
        <div class="col-5" data-label="Payment Status"><%= link_to '<i class="fas fa-wine-glass-alt"></i>'.html_safe, edit_cellar_bouteille_path(params[:id],b.id)  %></div>      </li>
      <% end %>
    <% end %>
  </ul>

</div>
<div class="wine_list">

  <ul class="responsive-table">
      <li class="table-header">
        <div class="colonne-1">Champagnes de <%= @cellar.name %></div>
        <div class="col-2">Domaine</div>
        <div class="col-3">Millesime</div>
        <div class="col-4">Apogée</div>
        <div class="col-5"></div>
      </li>
      <% @cellar.bouteilles.each do |b| %>
      <% if b.vin.categorie == "Champagne" %>
      <li class="table-row">
        <div class="colonne-1" data-label="Job Id"><%= b.vin.localite  %> <%= b.vin.appellation  %></div>
        <div class="col-2" data-label="Customer Name"> <%= b.vin.domaine  %></div>
        <div class="col-3" data-label="Amount"> <%= b.millesime  %></div>
        <div class="col-4" data-label="Payment Status">
          <% if b.vin.categorie == "Champagne" && b.vin.localite =="Champagne" %>
            <%= b.millesime.to_i + 3 %>
          <% else %>
            --
          <% end %>
        </div>
        <div class="col-5" data-label="Payment Status"><%= link_to '<i class="fas fa-wine-glass-alt"></i>'.html_safe, edit_cellar_bouteille_path(params[:id],b.id)  %></div>      </li>
      <% end %>
    <% end %>
  </ul>

</div>
<div class="wine_list">

  <ul class="responsive-table">
      <li class="table-header">
        <div class="colonne-1">Pétillants de <%= @cellar.name %></div>
        <div class="col-2">Domaine</div>
        <div class="col-3">Millesime</div>
        <div class="col-4">Apogée</div>
        <div class="col-5"></div>

      </li>
      <% @cellar.bouteilles.each do |b| %>

      <% if b.vin.categorie == "Petillant" %>
      <li class="table-row">
        <div class="colonne-1" data-label="Job Id"><%= b.vin.localite  %> <%= b.vin.appellation  %></div>
        <div class="col-2" data-label="Customer Name"> <%= b.vin.domaine  %></div>
        <div class="col-3" data-label="Amount"> <%= b.millesime  %></div>
        <div class="col-4" data-label="Payment Status"><%= b.millesime.to_i + 1 %></div>
        <div class="col-5" data-label="Payment Status"><%= link_to '<i class="fas fa-wine-glass-alt"></i>'.html_safe, edit_cellar_bouteille_path(params[:id],b.id)  %></div>      </li>
      <% end %>
    <% end %>
  </ul>

</div>

<p class="center"><%= link_to "Ajouter une bouteille déjà référencée à la cave", new_cellar_bouteille_path(params[:id]) %></p>

<div class='center'>

<%= link_to 'Supprimer la Cave', cellar_path(params[:id]),
          method: :delete,
          class: "btn btn-secondary btn-sm colorful",
          data: { confirm: "Etes-vous sûr de vouloir supprimer cette cave ?" }  %>

</div>
<%= link_to vins_path do %>
  <div class="addwine">
  <%=  image_tag "bouteille.png"%>
  </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWineCellar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">



  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/pages/contact.html.erb
<div class="contact">
  <p>
  Bonjour,
  </p>

  <p>
  Je m'appelle Hélène et j'ai réalisé ce site internet gratuit. Je l'ai réalisé suite à une formation au Wagon Paris. Je faisais partie du batch #200.
  Si vous avez une idée d'amélioration pour ce site ou si vous rencontrez un problème, vous pouvez me contacter sur <a href="https://www.linkedin.com/in/hélène-lioussou-86a143a2">LinkedIn</a>.
  </p>


  <p>
  Pour le moment, ce site est gracieux, et je ne saurais en assurer la viabilité à très long terme. Si ce site vous intéresse, faites-moi part de votre intérêt.
  </p>

  <p>
  Je vous remercie pour votre venue sur le site levindemonsieurjean.com et espère vous compter parmi les utilisateurs récurrents.
  </p>

  <p>Hélène</p>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>

  <div class='start'>
    <div class="pushthedoor">
      <%= link_to "Accéder à mes caves", cellars_path %>
    </div>
  </div>


<% else %>
  <div class='home'>
    <h4 class="enter"> </h4>
  </div>

<% end %>

<div class="stepscontainer">
  <div class="stepcard">
    <div class="center number">
      1
    </div>
    <div class ="text">
      <p>Créez votre compte sécurisé en cliquant sur login puis sign up et ajoutez une première cave dans votre espace personnel</p>
    </div>
  </div>

  <div class="stepcard">
    <div class="center number"> 2
    </div>
    <div class ="text">
      <p>Ajoutez des bouteilles dans votre cave virtuelle en quelques clics, qu'il s'agisse de Vins rouges, blancs, rosé, de Champagne ou de Vin Pétillant.</p>
    </div>
  </div>

  <div class="stepcard">
    <div class="center number "> 3 </div>
    <div class ="text"><p>Grâce à l'algorithme et au savoir de Monsieur Jean, découvrez quand déguster vos vins pour qu'ils dégagent tous leurs arômes.</p>
    </div>
  </div>
  </div>

<% if user_signed_in? %>

  <div class="center">
    <div class="bas-de-page">
      <p> Site réalisé par HL pour JL en Janvier 2019 <%= link_to "Contact", contact_path %></p>

    </div>
  </div>

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/vins/index.html.erb
<div class="wine_manager">

  <div class="left_part">

    <div class="liste">
      <h3 class="alignement">Vins référencés</h3>
      <% @vins.order("localite asc").order("appellation asc").each do |v| %>
        <ul>
          <li><%= v.categorie.upcase%> <%= v.localite.upcase %> <%= v.appellation %> <%= v.domaine %> <i><%= v.couleur %></i> <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, vin_path(v.id),
              method: :delete,
              data: { confirm: "Etes-vous sûr de vouloir supprimer ce vin ?" }  %>
          </li>
        </ul>
      <% end %>
    </div>

    <div class="action_part">
    <%= link_to "Nouveau", new_vin_path %>
    </div>

  </div>

  <div class="right_part">
    <h3>Ajouter en Cave</h3>
    <% @user.cellars.each do |c| %>
    <div class="cave_button funky_font"><%= link_to "#{c.name}", new_cellar_bouteille_path(c)  %></div>
    <% end %>
  </div>

</div>